language: php
php:
    - "5.5"
    - "5.6"
services:
    - mysql
before_script:
    - mysql -uroot < sql/milchkuh_test_table.sql
    - mysql -uroot < sql/test_stored_procedure.sql
    - composer self-update
    - composer install
script:
    - vendor/bin/phpunit
